name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build macOS binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/icon_logo_macos main.go
      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/icon_logo_linux main.go
      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/icon_logo.exe main.go
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/icon_logo_macos
            dist/icon_logo_linux
            dist/icon_logo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
